#!/usr/bin/env python3.6

#
# download python3.6.x from the website and install it
# pip3 install --upgrade pip
#

from PIL import Image, ImageDraw, ImageFont
import os.path
import re
import subprocess
import sys

SIZE_NORMAL = (800, 600)
ARGS        = sys.argv
image_path  = "default.png"

def detect_file(args):
    return list(filter(lambda f: os.path.isfile(f), args))[1]

def x(tuple):
    return tuple[0]

def y(tuple):
    return tuple[1]   

def write_text(canvas, point, label):
    _font = ImageFont.truetype("fonts/Helvetica-Normal.ttf", 15)
    canvas.text(point, label, font=_font, fill="black")

def add_circle_reverse(canvas, point_start=(0, 0), label="", diameter=100):
    _point_start = (x(point_start),            y(SIZE_NORMAL) - y(point_start) - diameter)
    point_end    = (x(point_start) + diameter, y(point_start) - diameter)
    _point_end   = (x(point_end),              y(SIZE_NORMAL) - y(point_end) - diameter)
    canvas.arc(xy=[_point_start, _point_end], start=0, end=360, fill="black")
    return _point_end

def move(point, dx, dy):
    return (point[0] + dx, point[1] - dy)

def add_circle(canvas, point_start=(0, 0), label="", diameter=100):
    point_start = (x(point_start),            y(point_start))
    point_end   = (x(point_start) + diameter, y(point_start) + diameter)
    canvas.arc(xy=[point_start, point_end], start=0, end=360, fill="black")
    write_text(canvas, move(point_end, -1 * diameter/2, diameter/2), label)
    return point_end

def add_oval(canvas, point_start=(0, 0), label="", diameter=100):
    point_start = (x(point_start),            y(point_start))
    point_end   = (x(point_start) + diameter * 2, y(point_start) + diameter)
    canvas.arc(xy=[point_start, point_end], start=0, end=360, fill="black")
    write_text(canvas, move(point_end, -1.7 * diameter, diameter/1.7), label)
    return point_end

def match(pattern, string):
    return re.match(pattern, string) != None

def is_image(filename):
    return match(".*(png|jpg|gif)$", filename)

def parse_dsl(dsl_path):
    with open(dsl_path) as f:
        content = f.readlines()
    return [x.strip() for x in content] 

def set_image_path(line):
    if is_image(line):
        global image_path
        image_path = line
    return line   

def convert_dsl(dsl_array):
    return list(map(lambda l: set_image_path(l), dsl_array))

def left(lsp):
    return lsp[0].strip()

def right(lsp):
    return lsp[1].strip()

def ovals_related(canvas, left_start, diameter, line, dict, size_inter_ovals=200):
    if match(".+>.+", line):
        ovals      = line.split(">")
        left_oval  = left(ovals)
        right_oval = right(ovals)

        if left_oval  in dict:
            left_end    = add_oval(canvas, left_start, dict[left_oval], diameter=diameter/2)
        if right_oval in dict:
            right_start = move(left_start, size_inter_ovals, 0)
            right_end   = add_oval(canvas, right_start, dict[right_oval],
                                   diameter=diameter/2)
            canvas.line(right_start, fill="black")
            canvas.line(move(left_end, 0, diameter/4) + 
                        move(right_end, -1 * diameter, diameter/4), fill="black")

def assign_values(line, dict):
    if match(".+:.+", line):
        lsp             = line.split(":")
        dict[left(lsp)] = right(lsp)
    return dict    

def draw(dsl_array):
    dict        = {}
    image       = Image.new(mode="RGB", size=SIZE_NORMAL, color="white")
    canvas      = ImageDraw.ImageDraw(image)
    start       = (12, 12)
    diameter    = 100

    for line in dsl_array:
        dict = assign_values(line, dict)
        ovals_related(canvas, start, diameter, line, dict)    

    del canvas
    image.save(image_path, "PNG")

instructions = convert_dsl(parse_dsl(detect_file(ARGS)))
draw(instructions)

subprocess.run(["open", image_path])
