#!/usr/bin/env python3.6

#
# download python3.6.x from the website and install it
# pip3 install --upgrade pip
#

from PIL import Image, ImageDraw

SIZE_NORMAL = (800, 600)

def x(tuple):
    return tuple[0]

def y(tuple):
    return tuple[1]   

def add_circle(image_draw, point_start=(0, 0)):
    _point_start  = (x(point_start),            y(SIZE_NORMAL) - y(point_start) - diameter)
    point_end     = (x(point_start) + diameter, y(point_start) - diameter)
    _point_end    = (x(point_end),              y(SIZE_NORMAL) - y(point_end) - diameter)
    image_draw.arc(xy=[_point_start, _point_end], start=0, end=360, fill="black")

image      = Image.new(mode="RGB", size=SIZE_NORMAL, color="white")
image_draw = ImageDraw.ImageDraw(image)

point_start = (12, 2)
diameter       = 100

add_circle(image_draw, point_start)

del image_draw
image.save("aaa.png", "PNG")
